### ISSUE TITLE
Enter API key for Premium

### ISSUE THREAD

**Issue by mkeller3** [tdowd/excel-geocoder#1]
Hello,

I noticed that you have listed ways to use the public, and enterprise keys.

' Domain and URL for Google API
Public Const gstrGeocodingDomain = "https://maps.googleapis.com"
Public Const gstrGeocodingURL = "/maps/api/geocode/xml?"
' TODO: Add support for Data Science Toolkit, Bing Geospatial, etc.

' set gblnBusiness = 1 to use the Enterprise Geocoder (requires clientID and key)
Public Const gblnBusiness = 0
' clientID and key from Enterprise Geocoder
Public Const gstrClientID = ""
Public Const gstrKey = ""

Do you know a way to use a premium api key?

**Comment by tdowd** [comment]
@mkeller3 trying to look into it this weekend

**Comment by tdowd** [comment]
@mkeller3 it looks like i may need to try and create a premium api key setup to get this working, so i will need to investigate a little bit more - thank you for letting me know

**Comment by mkeller3** [comment]
Ok thanks!

**Comment by mkeller3** [comment]
Any luck? If you create a free api key that would have the same output.

**Comment by tdowd** [comment]
I signed up for a Free API Key and did some testing. I just committed a bit of functionality on the .bas file to switch between the Enterprise Geocoder (client ID + key), the Premium plan (key only) and the free geocoder.

**Comment by mkeller3** [comment]
Thanks that worked!!

**Comment by tdowd** [comment]
Great!
