### ISSUE TITLE
Compile error: user-defined type not defined

### ISSUE THREAD

**Issue by Synfinity-buymyDJ** [tdowd/excel-geocoder#4]
So I tried to do just one address lookup but was stopped by this error and this screen. I'm not sure what is undefined

![image](https://user-images.githubusercontent.com/30158047/28182608-5d9a67dc-67d2-11e7-8f3f-caf8897394eb.png)

![image](https://user-images.githubusercontent.com/30158047/28182649-7437ffea-67d2-11e7-835f-ab2b3579800c.png)

**Comment by tdowd** [comment]
@Synfinity-buymyDJ let me try to recreate the issue and get back to you. Thanks!

**Comment by tdowd** [comment]
@Synfinity-buymyDJ within the Developer tab, can you go to Tools and then References in the top toolbar, and find "Microsoft XML, v6.0" and enable it? I attached a screenshot for reference.
![xml](https://user-images.githubusercontent.com/5632133/28295946-5965b0a8-6b2a-11e7-9869-bcc6ef950d4e.png)

**Comment by Synfinity-buymyDJ** [comment]
Awesome thanks so much @tdowd ! I am now getting the lat/long pairs seemlessly. Glad it was such an easy fix!

**Comment by tdowd** [comment]
Great!
